POST http://localhost:3001/api/people/
Content-Type: application/json

{
  "name": "Steve Rand",
  "number": "98-76-451230"
}

###
POST http://localhost:3001/api/people/
Content-Type: application/json

{
  "name": "Liisa Marttinen",
  "number": "040-243563"
}

###
# Validation of minimum length (3) in name
POST http://localhost:3001/api/people/
Content-Type: application/json

{
  "name": "no",
  "number": "987-456123"
}

# Validation of number
###
POST http://localhost:3001/api/people/
Content-Type: application/json

{
  "name": "Invalid Number 1",
  "number": "fail00"
}

###
POST http://localhost:3001/api/people/
Content-Type: application/json

{
  "name": "Invalid Number 2",
  "number": "1-22334455"
}

###
POST http://localhost:3001/api/people/
Content-Type: application/json

{
  "name": "Invalid Number 3",
  "number": "10-22-334455"
}